/**
 * grunt-respimg
 * https://github.com/nwtn/grunt-respimg
 *
 * Copyright (c) 2015 David Newton
 * Licensed under the MIT license.
 *
 * Automatically resizes image assets
 *
 * Portions borrowed liberally from:
 *    <https://github.com/andismith/grunt-responsive-images>, and
 *    <https://github.com/dbushell/grunt-svg2png>, and
 *    <https://github.com/JamieMason/grunt-imageoptim>, and
 *    <https://github.com/sindresorhus/grunt-svgmin>
 *
 * @author David Newton (http://twitter.com/newtron)
 * @version 0.2.0
 */

(function() {
	'use strict';

	var async =		require('async'),
		fs =		require('fs'),
		resemble =	require('node-resemble');

	var compareImages = function(data, assetExpected, assetGenerated) {
		if (data.dimensionDifference.width !== 0) {
			console.error('Difference in width');
			return false;
		}

		if (data.dimensionDifference.height !== 0) {
			console.error('Difference in height');
			return false;
		}

		if (data.misMatchPercentage !== '0.00') {
			console.error('Difference in image content');
			return false;
		}

		var fileSizeRatio = assetExpected.length / assetGenerated.length;
		if (fileSizeRatio < 0.9 || fileSizeRatio > 1.1) {
			console.error('Difference in file size');
			return false;
		}

		return true;
	}


	// List of tests to be run
	//
	// TODO: add more tests
	//
	// Note that images for expected results should be generated
	// directly with ImageMagick etc., not generated with this plugin
	//
	// TODO: do this with the SVG stuff; right now those are
	// generated by the plugin
	exports.respimg = {
		defaultOptions: function(test) {
			var assetExpected,
				assetGenerated,
				diff;

			async.series([

				// 1A-1-w320.jpg
				function(callback) {
					assetExpected = fs.readFileSync('test/expected/default/raster/1A-1-w320.jpg');
					assetGenerated = fs.readFileSync('test/generated/default/raster/1A-1-w320.jpg');
					diff = resemble(assetExpected).compareTo(assetGenerated).onComplete(function(data) {
						test.ok(compareImages(data, assetExpected, assetGenerated), '1A-1-w320.jpg: images don’t match');
						callback();
					});
				},

				// 1A-1-w640.jpg
				function(callback) {
					assetExpected = fs.readFileSync('test/expected/default/raster/1A-1-w640.jpg');
					assetGenerated = fs.readFileSync('test/generated/default/raster/1A-1-w640.jpg');
					diff = resemble(assetExpected).compareTo(assetGenerated).onComplete(function(data) {
						test.ok(compareImages(data, assetExpected, assetGenerated), '1A-1-w640.jpg: images don’t match');
						callback();
					});
				},

				// 1A-1-w1280.jpg
				function(callback) {
					assetExpected = fs.readFileSync('test/expected/default/raster/1A-1-w1280.jpg');
					assetGenerated = fs.readFileSync('test/generated/default/raster/1A-1-w1280.jpg');
					diff = resemble(assetExpected).compareTo(assetGenerated).onComplete(function(data) {
						test.ok(compareImages(data, assetExpected, assetGenerated), '1A-1-w1280.jpg: images don’t match');
						callback();
					});
				},

				// 3C-2-w320.png
				function(callback) {
					assetExpected = fs.readFileSync('test/expected/default/raster/3C-2-w320.png');
					assetGenerated = fs.readFileSync('test/generated/default/raster/3C-2-w320.png');
					diff = resemble(assetExpected).compareTo(assetGenerated).onComplete(function(data) {
						test.ok(compareImages(data, assetExpected, assetGenerated), '3C-2-w320.png: images don’t match');
						callback();
					});
				},

				// 3C-2-w640.png
				function(callback) {
					assetExpected = fs.readFileSync('test/expected/default/raster/3C-2-w640.png');
					assetGenerated = fs.readFileSync('test/generated/default/raster/3C-2-w640.png');
					diff = resemble(assetExpected).compareTo(assetGenerated).onComplete(function(data) {
						test.ok(compareImages(data, assetExpected, assetGenerated), '3C-2-w640.png: images don’t match');
						callback();
					});
				},

				// 3C-2-w1280.png
				function(callback) {
					assetExpected = fs.readFileSync('test/expected/default/raster/3C-2-w1280.png');
					assetGenerated = fs.readFileSync('test/generated/default/raster/3C-2-w1280.png');
					diff = resemble(assetExpected).compareTo(assetGenerated).onComplete(function(data) {
						test.ok(compareImages(data, assetExpected, assetGenerated), '3C-2-w1280.png: images don’t match');
						callback();
					});
				},

				// pdf-w320.png
				function(callback) {
					assetExpected = fs.readFileSync('test/expected/default/svg/pdf-w320.png');
					assetGenerated = fs.readFileSync('test/generated/default/svg/pdf-w320.png');
					diff = resemble(assetExpected).compareTo(assetGenerated).onComplete(function(data) {
						test.ok(compareImages(data, assetExpected, assetGenerated), 'pdf-w320.png: images don’t match');
						callback();
					});
				},

				// pdf-w640.png
				function(callback) {
					assetExpected = fs.readFileSync('test/expected/default/svg/pdf-w640.png');
					assetGenerated = fs.readFileSync('test/generated/default/svg/pdf-w640.png');
					diff = resemble(assetExpected).compareTo(assetGenerated).onComplete(function(data) {
						test.ok(compareImages(data, assetExpected, assetGenerated), 'pdf-w640.png: images don’t match');
						callback();
					});
				},

				// pdf-w1280.png
				function(callback) {
					assetExpected = fs.readFileSync('test/expected/default/svg/pdf-w1280.png');
					assetGenerated = fs.readFileSync('test/generated/default/svg/pdf-w1280.png');
					diff = resemble(assetExpected).compareTo(assetGenerated).onComplete(function(data) {
						test.ok(compareImages(data, assetExpected, assetGenerated), 'pdf-w1280.png: images don’t match');
						callback();
					});
				},

				// pdf.svg
				function(callback) {
					assetExpected = fs.readFileSync('test/expected/default/svg/pdf.svg', 'utf-8');
					assetGenerated = fs.readFileSync('test/generated/default/svg/pdf.svg', 'utf-8');
					test.ok(assetExpected === assetGenerated, 'pdf.svg: images don’t match');
					callback();
				},
			],

			function(err, results) {
				test.done();
			});
		},

		widthAsDir: function(test) {
			var assetExpected,
				assetGenerated,
				diff;

			async.series([

				// 320/1A-1.jpg
				function(callback) {
					assetExpected = fs.readFileSync('test/expected/widthAsDir/raster/320/1A-1.jpg');
					assetGenerated = fs.readFileSync('test/generated/widthAsDir/raster/320/1A-1.jpg');
					diff = resemble(assetExpected).compareTo(assetGenerated).onComplete(function(data) {
						test.ok(compareImages(data, assetExpected, assetGenerated), '320/1A-1.jpg: images don’t match');
						callback();
					});
				},

				// 640/1A-1.jpg
				function(callback) {
					assetExpected = fs.readFileSync('test/expected/widthAsDir/raster/640/1A-1.jpg');
					assetGenerated = fs.readFileSync('test/generated/widthAsDir/raster/640/1A-1.jpg');
					diff = resemble(assetExpected).compareTo(assetGenerated).onComplete(function(data) {
						test.ok(compareImages(data, assetExpected, assetGenerated), '640/1A-1.jpg: images don’t match');
						callback();
					});
				},

				// 1280/1A-1.jpg
				function(callback) {
					assetExpected = fs.readFileSync('test/expected/widthAsDir/raster/1280/1A-1.jpg');
					assetGenerated = fs.readFileSync('test/generated/widthAsDir/raster/1280/1A-1.jpg');
					diff = resemble(assetExpected).compareTo(assetGenerated).onComplete(function(data) {
						test.ok(compareImages(data, assetExpected, assetGenerated), '1280/1A-1.jpg: images don’t match');
						callback();
					});
				},

				// 320/3C-2.png
				function(callback) {
					assetExpected = fs.readFileSync('test/expected/widthAsDir/raster/320/3C-2.png');
					assetGenerated = fs.readFileSync('test/generated/widthAsDir/raster/320/3C-2.png');
					diff = resemble(assetExpected).compareTo(assetGenerated).onComplete(function(data) {
						test.ok(compareImages(data, assetExpected, assetGenerated), '320/3C-2.png: images don’t match');
						callback();
					});
				},

				// 640/3C-2.png
				function(callback) {
					assetExpected = fs.readFileSync('test/expected/widthAsDir/raster/640/3C-2.png');
					assetGenerated = fs.readFileSync('test/generated/widthAsDir/raster/640/3C-2.png');
					diff = resemble(assetExpected).compareTo(assetGenerated).onComplete(function(data) {
						test.ok(compareImages(data, assetExpected, assetGenerated), '640/3C-2.png: images don’t match');
						callback();
					});
				},

				// 1280/3C-2.png
				function(callback) {
					assetExpected = fs.readFileSync('test/expected/widthAsDir/raster/1280/3C-2.png');
					assetGenerated = fs.readFileSync('test/generated/widthAsDir/raster/1280/3C-2.png');
					diff = resemble(assetExpected).compareTo(assetGenerated).onComplete(function(data) {
						test.ok(compareImages(data, assetExpected, assetGenerated), '1280/3C-2.png: images don’t match');
						callback();
					});
				},

				// 320/pdf.png
				function(callback) {
					assetExpected = fs.readFileSync('test/expected/widthAsDir/svg/320/pdf.png');
					assetGenerated = fs.readFileSync('test/generated/widthAsDir/svg/320/pdf.png');
					diff = resemble(assetExpected).compareTo(assetGenerated).onComplete(function(data) {
						test.ok(compareImages(data, assetExpected, assetGenerated), '320/pdf.png: images don’t match');
						callback();
					});
				},

				// 640/pdf.png
				function(callback) {
					assetExpected = fs.readFileSync('test/expected/widthAsDir/svg/640/pdf.png');
					assetGenerated = fs.readFileSync('test/generated/widthAsDir/svg/640/pdf.png');
					diff = resemble(assetExpected).compareTo(assetGenerated).onComplete(function(data) {
						test.ok(compareImages(data, assetExpected, assetGenerated), '640/pdf.png: images don’t match');
						callback();
					});
				},

				// 1280/pdf.png
				function(callback) {
					assetExpected = fs.readFileSync('test/expected/widthAsDir/svg/1280/pdf.png');
					assetGenerated = fs.readFileSync('test/generated/widthAsDir/svg/1280/pdf.png');
					diff = resemble(assetExpected).compareTo(assetGenerated).onComplete(function(data) {
						test.ok(compareImages(data, assetExpected, assetGenerated), '1280/pdf.png: images don’t match');
						callback();
					});
				},

				// pdf.svg
				function(callback) {
					assetExpected = fs.readFileSync('test/expected/widthAsDir/svg/pdf.svg', 'utf-8');
					assetGenerated = fs.readFileSync('test/generated/widthAsDir/svg/pdf.svg', 'utf-8');
					test.ok(assetExpected === assetGenerated, 'pdf.svg: images don’t match');
					callback();
				},
			],

			function(err, results) {
				test.done();
			});
		}
	};
}());
